pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    credentialsId: 'github',
                    url: 'https://github.com/Clifftabu/alx-backend-python.git'
            }
        }

	stage('Install Python') {
	    steps {
        	sh 'apt-get update && apt-get install -y python3 python3-pip'
    		}
	}
        stage('Install Dependencies') {
            steps {
                sh 'pip3 install -r messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app --junitxml=report.xml'
            }
        }
        stage('Archive Test Results') {
            steps {
                junit 'report.xml'
            }
        }
    }
}

