pipeline{
    agent {
	docker{
		image 'python:3.11-slim'
		args '-u root:root'
		}
	

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    credentialsId: 'github',
                    url: 'https://github.com/Clifftabu/alx-backend-python.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r messaging_app/requirements.txt'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest messaging_app --junitxml=report.xml'
            }
        }
        stage('Archive Test Results') {
            steps {
                junit 'report.xml'
            }
        }
    }
}

