pipeline{
	agent any
	stages{
		stage('Clone Repository'){

			steps{
				git url: 'https://github.com/clifftabu/alx-backend-python.git', branch: 'main'
			}
		}
		stage('Install Dependencies') {
			steps{
				sh 'pip install -r requirements.txt'
			}
		}
		stage('Run Tests') {
			steps{
				sh 'pytest --junitxml=report.xml'
			}
		}
		stage('Archive Test Results'){
			steps{
				junit 'report.xml'
			}
		}
	}
}
